### ISSUE TITLE
Provide way to hardcode class

### ISSUE THREAD

**Issue by johnlindquist** [azu/gitbook-plugin-include-codeblock#10]
When you import a TypeScript file `.ts`:
The parser correctly finds `.ts` in the languages.json extensions for both `TypeScript` _and_ `XML`, then automatically chooses XML.

Because this is the correct behavior (I'm assuming `.ts` is a valid extension for XML), the only approach is tell the parser exactly which language you want to be provided to `class='lang-typescript'.`

Perhaps adding an explicit class as a third param is the solution:
`[import, hello-world.js, lang-typescript](hello-world.ts)`

**Comment by azu** [comment]
@johnlindquist Thanks for reporting.

Currently, gitbook-plugin-include-codeblock use [language-map](https://github.com/blakeembrey/language-map) for detecting lang type by `.ext`.

Oh, `.ts` is duplicated.
- https://github.com/blakeembrey/language-map/blob/b72edb8c2cb1b05d098782aa85dd2f573ed96ba3/languages.json#L4136
- https://github.com/blakeembrey/language-map/blob/b72edb8c2cb1b05d098782aa85dd2f573ed96ba3/languages.json#L4397

> Perhaps adding an explicit class as a third param is the solution:
> `[import, hello-world.js, lang-typescript](hello-world.ts)`

It is possible, I think.

[language-map](https://github.com/blakeembrey/language-map) has `"aceMode"` property for each language.

**Comment by azu** [comment]
I'm try to implement.

**Comment by azu** [comment]
I've implemeted suggested feature #11

**Comment by azu** [comment]
@johnlindquist I've released [1.7.0](https://github.com/azu/gitbook-plugin-include-codeblock/releases/tag/1.7.0).
Please try it :)

**Comment by johnlindquist** [comment]
Wow, that was fast :)

Seems to work perfectly. Thanks so much.
