### ISSUE TITLE
Highlight bug in language-detection for C++ codes

### ISSUE THREAD

**Issue by gdolle** [azu/gitbook-plugin-include-codeblock#21]
It seems that code highlighting does not work with C++ files.

It seems the parse put `c_cpp` for lang instead of `cpp`.

``` c_cpp
// c_cpp example
int a;
```

``` cpp
// cpp example
int a;
```

**Comment by azu** [comment]
Intesting.
https://github.com/blakeembrey/language-map/blob/b72edb8c2cb1b05d098782aa85dd2f573ed96ba3/languages.json#L431-L455 defined that the `aceMode` of `.cpp` file is `c_cpp`.
- https://github.com/azu/gitbook-plugin-include-codeblock/blob/e1efa58cf02ade1e8a17c000c09f0ff8e7a0edd8/src/language-detection.js#L26-L45 look up the `aceMode`.

Which is correct value `aliases` or `searchTerm`?
I don't know correct way...

**Comment by gdolle** [comment]
It should be `cpp` so one or another seems ok :)

**Comment by gdolle** [comment]
Hum actually, I maybe replied too fast. 
I'm not sure that `aliases` or `searchTerm` are better than `aceMode` if we look at the map for other languages.

Maybe we could just add a specific test for c++, and parse (remove) the lang like `/c_cpp/cpp/g`.

What do you think ?

**Comment by azu** [comment]
> We use Linguist to perform language detection and syntax highlighting. You can find out which keywords are valid in the languages YAML file.

via [Creating and highlighting code blocks - User Documentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Maybe, correct algorithm is defined in [github/linguist](https://github.com/github/linguist).

**Comment by azu** [comment]
> Maybe we could just add a specific test for c++, and parse (remove) the lang like /c_cpp/cpp/g.

I want to avoid special case, but it is simple solution.
I agree with @gdolle's suggestion that does `/c_cpp/cpp/g`.

**Comment by gdolle** [comment]
I agree with you @azu that it is just a workaround, it would be better to check github/linguist.
It seems that currently, [`highlight.js` is used with gitbook](https://github.com/GitbookIO/gitbook/issues/902)

**Comment by azu** [comment]
This is resolved by [2.2.0](https://github.com/azu/gitbook-plugin-include-codeblock/releases/tag/2.2.0) and close it
