### ISSUE TITLE
[title:"title"](path/to/file) cause unknown block tag

### ISSUE THREAD

**Issue by azu** [azu/gitbook-plugin-include-codeblock#24]
I found a issue on `title:` feature #20 #19 

OK:

```
[import, title:no-console.js](../../src/ESLint/no-console.js)
```

NG:

> Template render error: (ja/ESLint/README.md) [Line 28, Column 10]
>   unknown block tag: else (In file 'ja/ESLint/README.md')

```
[import, title:"no-console.js"](../../src/ESLint/no-console.js)
```

NG:

> Template render error: (ja/ESLint/README.md) [Line 28, Column 10]
>   unknown block tag: else (In file 'ja/ESLint/README.md')

```
[import, title:'no-console.js'](../../src/ESLint/no-console.js)
```

/cc @gdolle

**Comment by azu** [comment]
`:"` or `:'` is reserved syntax maybe on GitBook v3.
- https://github.com/GitbookIO/gitbook/issues/685

**Comment by gdolle** [comment]
@azu Ok I'll take a look. I think it could be a problem of escaping `"` or `'`

**Comment by azu** [comment]
I've got it.
This is issue of template. it is not caused from `:"`.

OK:

```
{{#if title}}
{{#if id}}
{% if file.type=="asciidoc" %}
> [[{{id}}]]link:{{originalPath}}[{{title}}]
{% else %}
> <a id="{{id}}" href="{{originalPath}}">{{title}}</a>
{% endif %}
{{else}}
{% if file.type=="asciidoc" %}
> [[{{title}}]]link:{{originalPath}}[{{title}}]
{% else %}
> <a id="{{title}}" href="{{originalPath}}">{{title}}</a>
{% endif %}
{{/if}}
{{else}}
```

NG:

```
{{#if title}}
    {{#if id}}
        {% if file.type=="asciidoc" %}
        > [[{{id}}]]link:{{originalPath}}[{{title}}]
        {% else %}
        > <a id="{{id}}" href="{{originalPath}}">{{title}}</a>
        {% endif %}
        {{else}}
        {% if file.type=="asciidoc" %}
        > [[{{title}}]]link:{{originalPath}}[{{title}}]
        {% else %}
        > <a id="{{title}}" href="{{originalPath}}">{{title}}</a>
        {% endif %}
    {{/if}}
{{else}}
```

We should remove padding space from each line.
I will pull request to fix this.

**Comment by gdolle** [comment]
Ok nice catch! 

Le 30 mai 2016 17:56:32 UTC+02:00, azu notifications@github.com a écrit :

> I've got it.
> This is issue of template. it is not caused from `:"`.
> 
> OK:
> 
> ```
> {{#if title}}
> {{#if id}}
> {% if file.type=="asciidoc" %}
> > [[{{id}}]]link:{{originalPath}}[{{title}}]
> {% else %}
> > <a id="{{id}}" href="{{originalPath}}">{{title}}</a>
> {% endif %}
> {{else}}
> {% if file.type=="asciidoc" %}
> > [[{{title}}]]link:{{originalPath}}[{{title}}]
> {% else %}
> > <a id="{{title}}" href="{{originalPath}}">{{title}}</a>
> {% endif %}
> {{/if}}
> {{else}}
> ```
> 
> NG:
> 
> ```
> {{#if title}}
>    {{#if id}}
>        {% if file.type=="asciidoc" %}
>        > [[{{id}}]]link:{{originalPath}}[{{title}}]
>        {% else %}
>        > <a id="{{id}}" href="{{originalPath}}">{{title}}</a>
>        {% endif %}
>        {{else}}
>        {% if file.type=="asciidoc" %}
>        > [[{{title}}]]link:{{originalPath}}[{{title}}]
>        {% else %}
>        > <a id="{{title}}" href="{{originalPath}}">{{title}}</a>
>        {% endif %}
>    {{/if}}
> {{else}}
> ```
> 
> We should remove padding space from each line.
> I will pull request to fix this.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/azu/gitbook-plugin-include-codeblock/issues/24#issuecomment-222519768

## 
- Guillaume DOLLÉ - Phd Student - MOCO Team
- Research Institute for Advanced Mathematics (IRMA - CNRS UMR7501)
- University of Strasbourg (UDS)
- Office: P104 - 7, rue René Descartes 67084 Strasbourg CEDEX FRANCE
- Phone: 03 68 85 02 87
- Email-pro: gdolle@unistra.fr
- Email: contact@gdolle.com

**Comment by azu** [comment]
I've pull request #25
This pull request drop code counting feature from default.
Sorry about that.

**Comment by gdolle** [comment]
Ok,I thought also that using an option like `numbering` to enable it would be better.
 ;-)

Le 30 mai 2016 18:23:47 UTC+02:00, azu notifications@github.com a écrit :

> I've pull request #25
> This pull request drop code counting feature from default.
> Sorry about that.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/azu/gitbook-plugin-include-codeblock/issues/24#issuecomment-222523662

## 
- Guillaume DOLLÉ - Phd Student - MOCO Team
- Research Institute for Advanced Mathematics (IRMA - CNRS UMR7501)
- University of Strasbourg (UDS)
- Office: P104 - 7, rue René Descartes 67084 Strasbourg CEDEX FRANCE
- Phone: 03 68 85 02 87
- Email-pro: gdolle@unistra.fr
- Email: contact@gdolle.com
