### ISSUE TITLE
Cannot assign languages other than aceMode

### ISSUE THREAD

**Issue by lwchkg** [azu/gitbook-plugin-include-codeblock#26]
Today I tried to include a .vb file and the plugin assigned "text" for syntax highlighting because this is the aceMode of .vb file.

This is BAD because my syntax highlighter can highlight .vb files properly, but this plugin blocks selection of this mode.

**Comment by azu** [comment]
https://github.com/blakeembrey/language-map/blob/b72edb8c2cb1b05d098782aa85dd2f573ed96ba3/languages.json#L4258-L4276
languages.json defined `.vb` as `"text"` for reasons unknown to me.

We need to improve [Hardcode class](https://github.com/azu/gitbook-plugin-include-codeblock#hardcoded-class) that allow to write `[import, lang-vb](hello-world.vb)`.

The result will be 

``````
```vb
content
```
``````

But, currently it will be

``````
```xml
content
```
``````

**Comment by azu** [comment]
I've pull request to add fallback #27

**Comment by azu** [comment]
I'v publish https://github.com/azu/gitbook-plugin-include-codeblock/releases/tag/1.9.1.

You can use hardcoded class for `.vb` lile this: `[import, lang-vb](hello-world.vb)`.

https://github.com/azu/gitbook-plugin-include-codeblock#hardcoded-class

**Comment by lwchkg** [comment]
Thanks for fixing. Actually the word aceMode is confusing, because we don't send the code to Ace editor.
