### ISSUE TITLE
### markers don't work

### ISSUE THREAD

**Issue by aslakhellesoy** [azu/gitbook-plugin-include-codeblock#33]
According to the [docs](https://github.com/azu/gitbook-plugin-include-codeblock#snippet-code), `###` should be a valid comment in front of a marker.

That's currently not the case - the marker is not found.

**Comment by azu** [comment]
fmm.
This feature is implemented by @gdolle .
After merge this feature and I've tweak docs.

Docs is wrong or Feature is missing?

**Comment by jcodeing** [comment]
Markers do not work
I downloaded the example found that the operation can not be normal markers
Help

**Comment by gdolle** [comment]
Actually it should work from `##`. I guess I did not include that case while proposing the pull request. But just adding the character `#` [here](https://github.com/azu/gitbook-plugin-include-codeblock/blob/master/src/marker.js#L17) ( so `[\*!\/#]`) should solve the problem.
@azu can you make the change ?

**Comment by azu** [comment]
Thanks for confirm.
Welcome to PR :)

**Comment by azu** [comment]
This is resolved by https://github.com/azu/gitbook-plugin-include-codeblock/releases/tag/2.2.0 and close it
