### ISSUE TITLE
Allow to put marker in xml

### ISSUE THREAD

**Issue by eiswind** [azu/gitbook-plugin-include-codeblock#63]
xml has a different way of writing comments. Maybe I'm jus dumb, but I fail to put markers for snippets in xml files. I tried various variants  but they are not recognized. Is there a way to achieve this?

**Comment by azu** [comment]
This feature have been introduced in #12 by @gdolle 
This feature is based on https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsnippet
I don't know how doxygen support XML.

Current implementation may support following style.
(I do not try it yet)

```xml
<!-- [marker] -->
<paragraph />
<!-- [marker] -->
```
https://github.com/azu/gitbook-plugin-include-codeblock/blob/e9756feca1ed434c22e8a332769b4bcc13f9d4ed/src/marker.js#L16-L17

**Comment by eiswind** [comment]
Thanks for pointing me to the right place in the code. After understanding the regex patterns I found that
```
<!--![vaadin]-->
```
works fine
