### ISSUE TITLE
Option to omit link to file

### ISSUE THREAD

**Issue by orlade** [azu/gitbook-plugin-include-codeblock#7]
When including files that are outside of the GitBook scope, the included link will be a 404. If this is expected, I would prefer to omit the link since it could be confusing.

Alternatively, if the referenced file is not in `_book`, copy it there.

An example would be including snippets from source files in a project in which the book lives under `/docs`.

**Comment by azu** [comment]
> the included link will be a 404. If this is expected

This is indeeded behavior.

> I would prefer to omit the link since it could be confusing.

I agree with.

Or if the referenced file is not in `_book`, throw Error.

The design of this plugin is for GitHub and GitBook.
It means that it work as a relative link in GitHub and work as a `CodeBlock` in GitBook.

**Comment by johnlindquist** [comment]
I've just manually ripped out the link in from https://github.com/azu/gitbook-plugin-include-codeblock/blob/master/src/parser.js#L65

``````
return "``` " + lang + "\n" + content + "\n```";
``````

My use case is explaining the same file broken into pieces:

```
Import `bootstrap`:
[import:1-1, lang-typescript](./code/src/main.ts)
The line above will blah, blah, blah

Import your App
[import:2-2, lang-typescript](./code/src/main.ts)


Bootstrap your App
[import:4-5, lang-typescript](./code/src/main.ts)
```

And having "main.ts" show up over and over is distracting.

![image](https://cloud.githubusercontent.com/assets/36073/14291070/e667218a-fb1e-11e5-8a4b-30bb79b98c66.png)

**Comment by azu** [comment]
If we introduced `pluginsConfig` like `"embed-template"`, can you resolve this issue?

`````` js
{
    "plugins": ["include-codeblock"],
    "pluginsConfig": {
        "include-codeblock": {
            "embed-template": "```${lang}\n${content}\n```"
        }
    }
}
``````

if `"embed-template"` is defined, use it instead of built-in template.

**Comment by johnlindquist** [comment]
@azu that's actually a pretty neat solution...

Maybe it could switch between templates if you need multiple variations?

``````
{
    "plugins": ["include-codeblock"],
    "pluginsConfig": {
        "include-codeblock": {
            "my-template": "```${lang}\n${content}\n```",
            "template-copyright": "```${content}\n copyright me```",
        }
    }
}
``````

```
[import, my-template](./src/code.js)
[import, template-copyright](./src/code.js)
```

?
